"""规则文件：把「杂乱的 hosts 风格输入」规范化成一份确定性的规则文件。

**输入**由人手写，不保证整洁，本模块全部容忍：

* 空行；``#`` 注释（整行或行尾）
* ``ip host1 host2 ...`` —— 多个 host 映射到同一个 ip
* 反序写法 ``host1 host2 ... ip`` —— 与上一种等价
* 非法内容逐项忽略，**不影响其余行**，并且每一处忽略都会被如实记进结果

**输出**由 :func:`render` 生成，**确定性**：同一份输入（同一 source）重新导入
必须得到逐字节相同的文件，便于 diff 与版本管理。

语义：

* host 一律走 :func:`envboard.core.model.normalize_host`（小写、去根点、去 ``*.``）
* 同一 host 出现多次且 ip 不同 → **后出现者胜**，并记进 :attr:`RulesImport.conflicts`
* 一行里某个 host 非法 → 只丢那一项，同一行的其它 host 照常保留

本模块是纯逻辑：只用标准库，不碰文件系统、不碰宿主。
"""

from __future__ import annotations

import ipaddress
from collections.abc import Mapping
from dataclasses import dataclass
from dataclasses import field
from typing import Any

from .errors import InvalidConfig
from .model import is_ip_literal
from .model import normalize_host
from .model import validate_host
from .model import validate_ip

#: 规则文件名的合法形式（与 ``<confdir>/rules/<name>.rules`` 同名空间）。
RULES_SUFFIX = ".rules"

#: 跳过原因 —— 稳定代码，UI 与 fixture 都按它断言，不要随意改字面量。
SKIP_TOO_FEW_TOKENS = "too-few-tokens"
SKIP_NO_IP_LITERAL = "no-ip-literal"
SKIP_INVALID_HOST = "invalid-host"

SKIP_REASONS = (SKIP_TOO_FEW_TOKENS, SKIP_NO_IP_LITERAL, SKIP_INVALID_HOST)

_HEADER = (
    "# envboard rules file — normalized `ip host...` lines.",
    "# Generated by envboard; re-import the source instead of editing this by hand.",
)


@dataclass(frozen=True)
class SkippedItem:
    """被忽略的一行（或一行里的一个 token）。"""

    line: int
    text: str
    reason: str
    detail: str = ""

    def to_json(self) -> dict[str, Any]:
        return {"line": self.line, "text": self.text, "reason": self.reason, "detail": self.detail}


@dataclass(frozen=True)
class HostConflict:
    """同一个 host 被映射到不同 ip：``kept`` 是最终生效的那个。"""

    host: str
    kept: str
    dropped: str

    def to_json(self) -> dict[str, Any]:
        return {"host": self.host, "kept": self.kept, "dropped": self.dropped}


@dataclass
class RulesImport:
    """一次解析的完整结果。"""

    entries: dict[str, str] = field(default_factory=dict)
    skipped: list[SkippedItem] = field(default_factory=list)
    conflicts: list[HostConflict] = field(default_factory=list)
    total_lines: int = 0
    blank_lines: int = 0
    comment_lines: int = 0
    data_lines: int = 0

    @property
    def accepted(self) -> int:
        return len(self.entries)

    @property
    def ips(self) -> int:
        return len(set(self.entries.values()))

    def to_json(self) -> dict[str, Any]:
        return {
            "entries": dict(self.entries),
            "accepted": self.accepted,
            "ips": self.ips,
            "conflicts": [c.to_json() for c in self.conflicts],
            "skipped": [s.to_json() for s in self.skipped],
            "stats": {
                "total_lines": self.total_lines,
                "blank_lines": self.blank_lines,
                "comment_lines": self.comment_lines,
                "data_lines": self.data_lines,
                "accepted": self.accepted,
                "skipped": len(self.skipped),
                "conflicts": len(self.conflicts),
            },
        }


def parse_hosts_text(text: str) -> RulesImport:
    """解析 hosts 风格文本，返回规范化结果（不抛异常，非法内容记进 ``skipped``）。"""
    result = RulesImport()
    # 有些编辑器会写 BOM；不剥掉的话第一行会解析失败
    for lineno, raw in enumerate(text.lstrip("\ufeff").splitlines(), start=1):
        result.total_lines += 1
        body = raw.split("#", 1)[0].strip()
        if not body:
            if raw.strip().startswith("#"):
                result.comment_lines += 1
            else:
                result.blank_lines += 1
            continue

        result.data_lines += 1
        tokens = body.split()
        if len(tokens) < 2:
            result.skipped.append(
                SkippedItem(lineno, body, SKIP_TOO_FEW_TOKENS, tokens[0] if tokens else "")
            )
            continue

        # 兼容两种写法：ip 在前是 hosts 文件惯例，ip 在后是不少团队的手写习惯。
        if is_ip_literal(tokens[0]):
            ip_token, host_tokens = tokens[0], tokens[1:]
        elif is_ip_literal(tokens[-1]):
            ip_token, host_tokens = tokens[-1], tokens[:-1]
        else:
            result.skipped.append(SkippedItem(lineno, body, SKIP_NO_IP_LITERAL))
            continue

        try:
            ip = validate_ip(ip_token)
        except InvalidConfig:
            result.skipped.append(SkippedItem(lineno, body, SKIP_NO_IP_LITERAL, ip_token))
            continue

        for token in host_tokens:
            if is_ip_literal(token):
                # 例：`1.2.3.4 5.6.7.8` —— 多出来的 IP 不是 host
                result.skipped.append(SkippedItem(lineno, body, SKIP_INVALID_HOST, token))
                continue
            try:
                host = validate_host(token)
            except InvalidConfig:
                result.skipped.append(SkippedItem(lineno, body, SKIP_INVALID_HOST, token))
                continue

            previous = result.entries.get(host)
            if previous is not None and previous != ip:
                result.conflicts.append(HostConflict(host, ip, previous))
            result.entries[host] = ip  # 后出现者胜

    return result


def _ip_sort_key(ip: str) -> tuple[int, bytes]:
    """按 IP 数值排序，避免 ``10.0.0.10`` 排在 ``10.0.0.2`` 前面。"""
    addr = ipaddress.ip_address(ip)
    return (addr.version, addr.packed)


def render_rules(entries: Mapping[str, str], *, source: str = "") -> str:
    """把 ``{host: ip}`` 渲染成确定性规则文件文本。

    同一份 ``entries`` + ``source`` 必须得到逐字节相同的结果。
    """
    normalized: dict[str, str] = {}
    for host, ip in entries.items():
        normalized[normalize_host(host)] = str(ip)

    by_ip: dict[str, list[str]] = {}
    for host, ip in normalized.items():
        by_ip.setdefault(ip, []).append(host)

    lines = list(_HEADER)
    if source:
        lines.append(f"# source: {source}")
    lines.append(f"# entries: {len(normalized)}  ip: {len(by_ip)}")
    lines.append("")
    for ip in sorted(by_ip, key=_ip_sort_key):
        lines.append(f"{ip} {' '.join(sorted(by_ip[ip]))}")
    return "\n".join(lines) + "\n"
