//! 确定性渲染 —— 契约见 `spec/rules.md` §6。
//!
//! 同一份 entries + source 必须得到**逐字节**相同的文本，所以这里的每一处
//! 空格、破折号与排列顺序都是契约的一部分，不是风格问题。

use std::collections::BTreeMap;

use crate::{Error, ErrorCode, parse_ip_literal};

use super::host::normalize_host;

const HEADER: [&str; 2] = [
    "# envboard rules file — normalized `ip host...` lines.",
    "# Generated by envboard; re-import the source instead of editing this by hand.",
];

/// `field` 路径：渲染失败时对外报这个。
pub const ENTRIES_FIELD: &str = "rules.entries";

/// 把 `{host: ip}` 渲染成确定性的规则文件文本。
///
/// 排序规则：ip 按**数值**序（先地址族，IPv4 全部在 IPv6 之前；同族按地址字节序），
/// 同一行内的 host 按 Unicode 码点序（UTF-8 字节序与码点序一致，所以直接排即可）。
pub fn render_rules(entries: &BTreeMap<String, String>, source: &str) -> Result<String, Error> {
    let mut normalized: BTreeMap<String, String> = BTreeMap::new();
    for (host, ip) in entries {
        let host = normalize_host(host);
        // 渲染前的 entries 必须已归一化。两个键归一化后撞车 → 响亮失败，
        // 不依赖映射的迭代顺序静默取一个（相对 v1 的收紧，见 `spec/rules.md` §6.8）。
        if normalized.contains_key(&host) {
            return Err(Error::at(
                ErrorCode::InvalidConfig,
                ENTRIES_FIELD,
                format!("two entries normalize to the same host {host:?}; refusing to pick one"),
            ));
        }
        normalized.insert(host, ip.clone());
    }

    let mut by_ip: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (host, ip) in normalized {
        by_ip.entry(ip).or_default().push(host);
    }

    let mut groups: Vec<(String, Vec<String>)> = by_ip.into_iter().collect();
    groups.sort_by_key(|(ip, _)| sort_key(ip));
    for (_, hosts) in groups.iter_mut() {
        // Python 的 sorted() 按码点序；Rust 的 String Ord 是 UTF-8 字节序，
        // 两者顺序一致。
        hosts.sort();
    }

    let total_hosts: usize = groups.iter().map(|(_, hosts)| hosts.len()).sum();
    let mut lines: Vec<String> = HEADER.iter().map(|line| (*line).to_string()).collect();
    if !source.is_empty() {
        lines.push(format!("# source: {source}"));
    }
    // 注意：`N` 与 `ip:` 之间是**两个空格**。
    lines.push(format!("# entries: {total_hosts}  ip: {}", groups.len()));
    lines.push(String::new());
    for (ip, hosts) in &groups {
        lines.push(format!("{ip} {}", hosts.join(" ")));
    }

    let mut out = lines.join("\n");
    out.push('\n');
    Ok(out)
}

/// 排序键：`(地址族, 地址字节)` —— 这样 `10.0.0.2` 排在 `10.0.0.10` 之前。
///
/// 解析不了的 ip 文本退化成"排在最后并按文本排"，而不是 panic：
/// entries 只可能来自解析器，但渲染是持久化前的最后一道关，宁可有序也不要崩。
fn sort_key(ip: &str) -> (u8, Vec<u8>, String) {
    match parse_ip_literal(ip) {
        Some(std::net::IpAddr::V4(addr)) => (4, addr.octets().to_vec(), String::new()),
        Some(std::net::IpAddr::V6(addr)) => (6, addr.octets().to_vec(), String::new()),
        None => (255, Vec::new(), ip.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entries(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(h, i)| ((*h).to_string(), (*i).to_string()))
            .collect()
    }

    #[test]
    fn renders_the_exact_contract_bytes() {
        let text = render_rules(&entries(&[("a.example.com", "10.0.0.1")]), "").unwrap();
        let expected = concat!(
            "# envboard rules file — normalized `ip host...` lines.\n",
            "# Generated by envboard; re-import the source instead of editing this by hand.\n",
            "# entries: 1  ip: 1\n",
            "\n",
            "10.0.0.1 a.example.com\n",
        );
        assert_eq!(text, expected);
    }

    #[test]
    fn empty_entries_still_render_a_valid_file() {
        let text = render_rules(&BTreeMap::new(), "").unwrap();
        assert!(text.ends_with("# entries: 0  ip: 0\n\n"), "got: {text:?}");
    }

    #[test]
    fn ips_sort_numerically_and_hosts_lexically() {
        let text = render_rules(
            &entries(&[
                ("b.example.com", "10.0.0.10"),
                ("a.example.com", "10.0.0.2"),
                ("c.example.com", "10.0.0.2"),
                ("v6.example.com", "2001:db8::1"),
            ]),
            "handwritten",
        )
        .unwrap();
        // 5 行头：两行固定 header + source + 计数 + 空行
        let body: Vec<&str> = text.lines().skip(5).collect();
        assert_eq!(
            body,
            vec![
                "10.0.0.2 a.example.com c.example.com",
                "10.0.0.10 b.example.com",
                "2001:db8::1 v6.example.com",
            ]
        );
        assert!(text.contains("# source: handwritten\n"));
    }

    #[test]
    fn colliding_normalized_keys_fail_loudly() {
        let error = render_rules(
            &entries(&[
                ("A.example.com", "10.0.0.1"),
                ("a.example.com.", "10.0.0.2"),
            ]),
            "",
        )
        .unwrap_err();
        assert_eq!(error.code, ErrorCode::InvalidConfig);
        assert_eq!(error.field.as_deref(), Some(ENTRIES_FIELD));
    }

    #[test]
    fn render_is_byte_stable_across_reparse() {
        let first = render_rules(
            &entries(&[("a.example.com", "10.0.0.1"), ("b.example.com", "10.0.0.2")]),
            "s",
        )
        .unwrap();
        let reparsed = super::super::parse_hosts_text(&first);
        let second = render_rules(&reparsed.entries, "s").unwrap();
        assert_eq!(first, second);
    }
}
